name: 'Cybersecurity Actions'
author: 'Dinis Cruz'
description: 'Run a type of reporting on your repository'
inputs:
  scan-type:
    descripton: 'Type of scan to run [ Container Scan (CS), Bad Practices (BP), Vulnerability Scan (VS), Secret Scan (SS) ]'
    required: true
  prosp-filepath:
    description: 'Path within the scanned repository whe the prospector profile file is'
    default: ''
  prosp-cmd:
    description: 'Aditional command line arguments to be passed to prospector'
    default: ''
  radon-cmd:
    description: 'Aditional command line arguments to be passed to radon'
    default: ''
  files-toscan:
    description: 'Files to perform Bad Practices on'
    deafult: ''
  bp-isblocking:
    description: 'Fail the workflow if the Bad Practices Scan finds any problems'
    default: 'true'
  horusec-filepath:
    description: 'Path within the scanned repository whe the horusec config file is'
    default: ''
  horusec-cmd:
    description: 'Aditional command line arguments to be passed to horusec'
    default: ''
  vs-isblocking:
    description: 'Fail the workflow if the Vulnerability Scan finds vulnerabilities'
    default: 'true'
  gitleaks-cmd:
    description: 'Additional command line arguments to be passed to gitleaks'
    default: ''
  secrets-filepath:
    description: 'Hash of secrets to ignore during gitleaks run'
    default: ''
  ss-isblocking:
    description: 'Fail the workflow if the Secrets Scan finds secrets not accepted'
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Entrypoint
      run: >
            ${{ github.action_path }}/entrypoint.sh 
            --action-path ${{ github.action_path }} 
            --repo-name ${{ github.event.repository.name }}
            --scan-type ${{ inputs.scan-type }}
            --prosp-filepath ${{ inputs.prosp-filepath }}
            --prosp-cmd ${{ inputs.prosp-cmd }}
            --radon-cmd ${{ inputs.radon-cmd }}
            --files-toscan ${{ inputs.files-toscan }}
            --bp-isblocking ${{ inputs.bp-isblocking }}
            --horusec-filepath ${{ inputs.horusec-filepath }}
            --horusec-cmd ${{ inputs.horusec-cmd }}
            --vs-isblocking ${{ inputs.vs-isblocking }}
            --gitleaks-cmd ${{ inputs.gitleaks-cmd }}
            --secrets-filepath ${{ inputs.secrets-filepath }}
            --ss-isblocking ${{ inputs.ss-isblocking }}
      shell: bash
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reports
        path: Reports/
